# .github/workflows/deploy.yml

name: Deploy Chess Club

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Checkout
        run: |
          echo "GitHub Workspace: $GITHUB_WORKSPACE"
          echo "Repository files:"
          ls -la
          echo "Package.json exists?"
          test -f package.json && echo "Yes" || echo "No"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Verify package files
        run: |
          echo "Current working directory:"
          pwd
          echo "Package.json contents:"
          cat package.json
          echo "Package-lock.json exists?"
          test -f package-lock.json && echo "Yes" || echo "No"

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint
        
      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist